version: "3.7"

services:
  guestbook:
    image: ghcr.io/naufaldi/guestbook:prod
    labels:
      caddy: dev.faldi.xyz
      caddy.reverse_proxy: "{{upstreams 8080}}"
      com.centurylinklabs.watchtower.enable: "true"
    expose:
      - "8080"
    secrets:
      - db-password
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=guestbook
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - edge
      - guestbook-private
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=guestbook
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - guestbook-private
volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  edge:
    external: true
  guestbook-private:
    driver: bridge